
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT"
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"